class HistoryLabelHelper {
  static Map<String, String> createLabels({
    required String english,
    required String arabic,
    String? spanish,
    String? chinese,
    String? hindi,
    String? bengali,
    String? portuguese,
    String? russian,
    String? japanese,
    String? punjabi,
    String? german,
    String? korean,
    String? french,
    String? telugu,
    String? marathi,
    String? turkish,
    String? tamil,
    String? vietnamese,
    String? urdu,
    String? persian,
    String? polish,
    String? ukrainian,
    String? romanian,
    String? dutch,
    String? thai,
    String? indonesian,
    String? malay,
    String? swahili,
    String? italian,
    String? greek,
  }) {
    return {
      'en': english,
      'ar': arabic,
      if (spanish != null) 'es': spanish,
      if (chinese != null) 'zh': chinese,
      if (hindi != null) 'hi': hindi,
      if (bengali != null) 'bn': bengali,
      if (portuguese != null) 'pt': portuguese,
      if (russian != null) 'ru': russian,
      if (japanese != null) 'ja': japanese,
      if (punjabi != null) 'pa': punjabi,
      if (german != null) 'de': german,
      if (korean != null) 'ko': korean,
      if (french != null) 'fr': french,
      if (telugu != null) 'te': telugu,
      if (marathi != null) 'mr': marathi,
      if (turkish != null) 'tr': turkish,
      if (tamil != null) 'ta': tamil,
      if (vietnamese != null) 'vi': vietnamese,
      if (urdu != null) 'ur': urdu,
      if (persian != null) 'fa': persian,
      if (polish != null) 'pl': polish,
      if (ukrainian != null) 'uk': ukrainian,
      if (romanian != null) 'ro': romanian,
      if (dutch != null) 'nl': dutch,
      if (thai != null) 'th': thai,
      if (indonesian != null) 'id': indonesian,
      if (malay != null) 'ms': malay,
      if (swahili != null) 'sw': swahili,
      if (italian != null) 'it': italian,
      if (greek != null) 'el': greek,
    };
  }
}
